### PR TITLE
"Change binary annotation to existing system

### LINKED ISSUE #38: Fix the bininary Operator annotation
# Description

Fix the bininary Operator annotation by using the checks made by fonto in binaryoperator.ts

# Sub-tasks

Atomized tasks that cannot be broken down further.

- [x] Copy the code
- [x] Trefactor to the point it works with our implementation
- [x] Fix the non-working tests

### PR DESCRIPTION
**Pull request by HectorPeeters**
# Description

Since the old implementation didn't work correctly, we are reverting back to the existing type system.

Closes #38 

# Changes

1. Remove our proof of concept implementation
2. Add the existing system

# Deletes Source Branch?

Yes:    Work is done, the branch can be safely deleted.

# How Many Approvals?

* 2 Approvals (Normal features and bugs)

### CODE REVIEW

**Review by FBroy — APPROVED** [review]
We've tried

File: src/expressions/operators/arithmetic/BinaryOperator.ts [hunk 1]
```diff
@@ -506,10 +506,7 @@ class BinaryOperator extends Expression {
 
 				if (this._evaluateFunction && this.type) {
 					return sequenceFactory.singleton(
```
Comment (yuanzexiong) [inline src/expressions/operators/arithmetic/BinaryOperator.ts:508]: Okay so this line was actually here until we removed it and then we fixed the problem by adding it back?!

**Review by yuanzexiong — APPROVED** [review]
Shame that it has been reverted but well at least we ruled out an option.
