### PR TITLE
117 implement simple map expr

### LINKED ISSUE #117: Implement simpleMapExpr
# Description
The simpleMapExpr was wrongly implemented and currently only returns undefined. It should be correctly implemented and annotate the correct type.

## Subtasks

- [x] Implement simpleMapExpr

### PR DESCRIPTION
**Pull request by maanpalle**
# Pull Request

## Description

This pull request adds annotation to the simpleMapExpr node, while implementing this we noticed that there is a better way to implement the annotation of the sequenceOperator. This by annotating the node if all the the types of the elements are the same.

Closes #117 

## Changes

1. Expanded on the SequenceOperatorAnnotation
2. Fixed the simpleMapExpressionAnnotation
3. Fixed the tests
4. Fixed the comments

## Deletes Source Branch?

Yes:    Work is done, the branch can be safely deleted.

## How Many Approvals?

* 2 Approvals (Normal features and bugs)

### CODE REVIEW

**Comment by MTimmerije** [comment]
delet this

File: src/typeInference/annotateSimpleMapExpr.ts [hunk 1]
```diff
@@ -8,13 +13,24 @@ import { AnnotationContext } from './AnnotationContext';
...
-	// 	mult: SequenceMultiplicity.EXACTLY_ONE,
-	// };
-
-	// astHelper.insertAttribute(ast, 'type', seqType);
-	// return seqType;
-	return undefined;
+export function annotateSimpleMapExpr(
+	ast: IAST,
+	context: AnnotationContext,
+	annotate: (ast: IAST, context: AnnotationContext) => SequenceType
```
Comment (HectorPeeters) [inline src/typeInference/annotateSimpleMapExpr.ts]: Since we're not passing annotate to any of the other annotation functions, wouldn't it be better to annotate all the pathExpr nodes before calling this function and then pass those as arguments. That way, its more consistent with the rest of the codebase.

**Comment by HectorPeeters** [comment]
Everything else looks good to me!

File: src/typeInference/annotateSimpleMapExpr.ts (hunk 1 above)
Comment (maanpalle) [reply src/typeInference/annotateSimpleMapExpr.ts]: yup

**Review by MTimmerije — APPROVED** [review]
Looks fine to me, nice.
