### PR TITLE
Fix a few TODOs

### LINKED ISSUE #77: Resolve TODOs
# Description

Resolve the different TODOs around the code base.

some of the TODOs can be searched using keyword `TODO: Annotation not yet implemented`

# Sub-tasks

- [ ] annotateContextItemExpr.ts
- [x] annotateBinaryOperator.ts
- [ ] annotateUnaryLookup.ts
- [x] annotateTypeswitchOperator.ts
- [x] annotateTypeSwitchOperator.ts
- [x] SequenceOperator.ts
- [x] Unary.ts
- [x] valueCompare.ts
- [x] builtInFunctions_dataTypeConstructors.ts

### PR DESCRIPTION
**Pull request by FBroy**
# Description

Fixes the TODOs that we've created throughout the code base.

## Deletes Source Branch?

Yes:    Work is done, the branch can be safely deleted.

## How Many Approvals?

* 2 Approvals (Normal features and bugs)

### CODE REVIEW

File: src/expressions/operators/arithmetic/Unary.ts [hunk 1]
```diff
@@ -6,12 +6,7 @@ import sequenceFactory from '../../dataTypes/sequenceFactory';
 import { SequenceType, ValueType } from '../../dataTypes/Value';
 import Expression from '../../Expression';
 
-type UnaryLookupTable = {
-	[key: number]: ValueType;
-};
-
-// TODO: fix this?
-const UNARY_LOOKUP: UnaryLookupTable = {
+const UNARY_LOOKUP: { [key: number]: ValueType } = {
```
Comment (HectorPeeters) [inline src/expressions/operators/arithmetic/Unary.ts:9]: That looks a lot cleaner indeed!

File: src/typeInference/annotateAST.ts [hunk 2]
```diff
@@ -287,21 +287,38 @@ export function annotate(ast: IAST, staticContext: StaticContext): SequenceType
...
 
 		case 'quantifiedExpr':
 			astHelper.getChildren(ast, '*').map((a) => annotate(a, staticContext));
 			return annotateQuantifiedExpr(ast);
 
+		// XQuery nodes
+		case 'x:stackTrace':
+			return annotate(astHelper.getChildren(ast, '*')[2], staticContext);
+
+		case 'resultExpr':
```
Comment (HectorPeeters) [inline src/typeInference/annotateAST.ts]: I don't think this one should be placed here since its not really a separate AST node. Its more a property of the typeswitchExpr.

File: src/typeInference/annotateTypeSwitchOperator.ts [hunk 3]
```diff
@@ -1,7 +1,63 @@
...
+	ast: IAST,
+	argumentType: SequenceType,
+	caseClausesReturns: SequenceType[],
+	defaultCaseReturn: SequenceType
+): SequenceType {
+	const caseClausesConditions = astHelper.getChildren(ast, 'typeswitchExprCaseClause');
+	// Do the switch case to see what will be returned
+	for (let i = 0; i < caseClausesReturns.length; i++) {
+		// The typeswitch either contains a sequenceType with a single type or an 'or' statement
+		if (caseClausesConditions[i][1][0] === 'sequenceType') {
```
Comment (HectorPeeters) [inline src/typeInference/annotateTypeSwitchOperator.ts]: Really small remark but maybe this can be a switch? Might be a little bit cleaner.

File: test/specs/annotation.tests.ts [hunk 4]
```diff
@@ -275,6 +275,21 @@ describe('Annotating inline functions', () => {
 	});
 });
 
+describe('Annotating typeswitch expression', () => {
```
Comment (HectorPeeters) [inline test/specs/annotation.tests.ts:277]: Nice! test!

File: src/typeInference/annotateAST.ts (hunk 2 above)
Comment (FBroy) [reply src/typeInference/annotateAST.ts]: Indeed, I was testing around and forgot to remove them, good catch.

File: src/expressions/operators/arithmetic/Unary.ts (hunk 1 above)
Comment (yuanzexiong) [reply src/expressions/operators/arithmetic/Unary.ts:9]: Emm duplicated again, it's being done in the review changes branch which is still on going. But not a problem by itself.

File: src/typeInference/annotateTypeSwitchOperator.ts [hunk 5]
```diff
@@ -1,7 +1,65 @@
...
+		if ((conditon as IAST[]).length === 2) {
+			if (argumentType.mult === SequenceMultiplicity.EXACTLY_ONE) {
+				return returnType;
+			}
+		} else {
+			if (argumentType.mult === stringToSequenceMultiplicity(conditon[2][1])) {
+				return returnType;
+			}
+		}
+	}
```
Comment (yuanzexiong) [inline src/typeInference/annotateTypeSwitchOperator.ts:63]: Awesome, one less type to worry about!

**Review by yuanzexiong — APPROVED** [review]

**Review by HectorPeeters — APPROVED** [review]

File: src/expressions/dataTypes/Value.ts [hunk 6]
```diff
@@ -312,3 +312,16 @@ export function stringToSequenceType(input: string): SequenceType {
 			};
 	}
 }
+
+export function stringToSequenceMultiplicity(input: string): SequenceMultiplicity {
+	switch (input) {
```
Comment (MTimmerije) [inline src/expressions/dataTypes/Value.ts:317]: This could potentially be done more nicely, by doing `switch(input[input.length - 1])`, then it also works for entire type strings.

**Review by MTimmerije — APPROVED** [review]
Besides this one small nitpick, the whole thing looks quite good.

File: src/expressions/dataTypes/Value.ts (hunk 6 above)
Comment (FBroy) [reply src/expressions/dataTypes/Value.ts:317]: Where I use it, it only gives the +, * or ? operators, hence this should be enough.
